
# python run_editing_weights_loraMerge.py --target_model_id="/bime-munin/xiruod/llama2_SHAC/n200/set-6114-quantization-epoch3-llama-2-7B-loraR-8" --source_model_id="/bime-munin/xiruod/llama2_SHAC/n200/Reverse-Source-set-6114-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_SHAC/n200/Weights_ReverseSource/" --quantization --gpu="2" --lambda1='1' --lambda2='0' --cpuOps
# python run_editing_weights_loraMerge.py --target_model_id="/bime-munin/xiruod/llama2_SHAC/n200/set-11063-quantization-epoch3-llama-2-7B-loraR-8" --source_model_id="/bime-munin/xiruod/llama2_SHAC/n200/Reverse-Source-set-11063-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_SHAC/n200/Weights_ReverseSource/" --quantization --gpu="2" --lambda1='1' --lambda2='0' --cpuOps
# python run_editing_weights_loraMerge.py --target_model_id="/bime-munin/xiruod/llama2_SHAC/n200/set-1152-quantization-epoch3-llama-2-7B-loraR-8" --source_model_id="/bime-munin/xiruod/llama2_SHAC/n200/Reverse-Source-set-1152-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_SHAC/n200/Weights_ReverseSource/" --quantization --gpu="2" --lambda1='1' --lambda2='0' --cpuOps

# python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_SHAC/n200/Weights_ReverseSource/set-6114-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.0-lambda2_0.0-added.pth" --output_dir="/bime-munin/xiruod/llama2_SHAC/n200/Inferences_ReverseSource/" --quantization --gpu="2" --device="cuda:0" --batch_size=8 --cpuOps --dataset="SHAC"
# python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_SHAC/n200/Weights_ReverseSource/set-11063-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.0-lambda2_0.0-added.pth" --output_dir="/bime-munin/xiruod/llama2_SHAC/n200/Inferences_ReverseSource/" --quantization --gpu="2" --device="cuda:0" --batch_size=8 --cpuOps --dataset="SHAC"
# python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_SHAC/n200/Weights_ReverseSource/set-1152-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.0-lambda2_0.0-added.pth" --output_dir="/bime-munin/xiruod/llama2_SHAC/n200/Inferences_ReverseSource/" --quantization --gpu="2" --device="cuda:0" --batch_size=8 --cpuOps --dataset="SHAC"

# python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_SHAC/n200/Inferences_ReverseSource/inference_set-6114-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.0-lambda2_0.0-added" --output_dir="../output/tmpData/SHAC_ReverseSource/" --nRuns=5 --dataset="SHAC"
# python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_SHAC/n200/Inferences_ReverseSource/inference_set-11063-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.0-lambda2_0.0-added" --output_dir="../output/tmpData/SHAC_ReverseSource/" --nRuns=5 --dataset="SHAC"
# python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_SHAC/n200/Inferences_ReverseSource/inference_set-1152-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.0-lambda2_0.0-added" --output_dir="../output/tmpData/SHAC_ReverseSource/" --nRuns=5 --dataset="SHAC"





# python run_editing_weights_loraMerge.py --target_model_id="/bime-munin/xiruod/llama2_SHAC/n200/set-6114-quantization-epoch3-llama-2-7B-loraR-8" --source_model_id="/bime-munin/xiruod/llama2_SHAC/n200/Reverse-Source-set-6114-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_SHAC/n200/Weights_ReverseSource/" --quantization --gpu="2" --lambda1='1' --lambda2='1' --cpuOps
# python run_editing_weights_loraMerge.py --target_model_id="/bime-munin/xiruod/llama2_SHAC/n200/set-11063-quantization-epoch3-llama-2-7B-loraR-8" --source_model_id="/bime-munin/xiruod/llama2_SHAC/n200/Reverse-Source-set-11063-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_SHAC/n200/Weights_ReverseSource/" --quantization --gpu="2" --lambda1='1' --lambda2='1' --cpuOps
# python run_editing_weights_loraMerge.py --target_model_id="/bime-munin/xiruod/llama2_SHAC/n200/set-1152-quantization-epoch3-llama-2-7B-loraR-8" --source_model_id="/bime-munin/xiruod/llama2_SHAC/n200/Reverse-Source-set-1152-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_SHAC/n200/Weights_ReverseSource/" --quantization --gpu="2" --lambda1='1' --lambda2='1' --cpuOps

# python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_SHAC/n200/Weights_ReverseSource/set-6114-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.0-lambda2_1.0-added.pth" --output_dir="/bime-munin/xiruod/llama2_SHAC/n200/Inferences_ReverseSource/" --quantization --gpu="2" --device="cuda:0" --batch_size=8 --cpuOps --dataset="SHAC"
# python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_SHAC/n200/Weights_ReverseSource/set-11063-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.0-lambda2_1.0-added.pth" --output_dir="/bime-munin/xiruod/llama2_SHAC/n200/Inferences_ReverseSource/" --quantization --gpu="2" --device="cuda:0" --batch_size=8 --cpuOps --dataset="SHAC"
# python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_SHAC/n200/Weights_ReverseSource/set-1152-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.0-lambda2_1.0-added.pth" --output_dir="/bime-munin/xiruod/llama2_SHAC/n200/Inferences_ReverseSource/" --quantization --gpu="2" --device="cuda:0" --batch_size=8 --cpuOps --dataset="SHAC"

# python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_SHAC/n200/Inferences_ReverseSource/inference_set-6114-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.0-lambda2_1.0-added" --output_dir="../output/tmpData/SHAC_ReverseSource/" --nRuns=5 --dataset="SHAC"
# python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_SHAC/n200/Inferences_ReverseSource/inference_set-11063-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.0-lambda2_1.0-added" --output_dir="../output/tmpData/SHAC_ReverseSource/" --nRuns=5 --dataset="SHAC"
# python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_SHAC/n200/Inferences_ReverseSource/inference_set-1152-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.0-lambda2_1.0-added" --output_dir="../output/tmpData/SHAC_ReverseSource/" --nRuns=5 --dataset="SHAC"





# python run_editing_weights_loraMerge.py --target_model_id="/bime-munin/xiruod/llama2_SHAC/n200/set-6114-quantization-epoch3-llama-2-7B-loraR-8" --source_model_id="/bime-munin/xiruod/llama2_SHAC/n200/Reverse-Source-set-6114-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_SHAC/n200/Weights_ReverseSource/" --quantization --gpu="2" --lambda1='1.5' --lambda2='0.5' --cpuOps
# python run_editing_weights_loraMerge.py --target_model_id="/bime-munin/xiruod/llama2_SHAC/n200/set-11063-quantization-epoch3-llama-2-7B-loraR-8" --source_model_id="/bime-munin/xiruod/llama2_SHAC/n200/Reverse-Source-set-11063-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_SHAC/n200/Weights_ReverseSource/" --quantization --gpu="2" --lambda1='1.5' --lambda2='0.5' --cpuOps
# python run_editing_weights_loraMerge.py --target_model_id="/bime-munin/xiruod/llama2_SHAC/n200/set-1152-quantization-epoch3-llama-2-7B-loraR-8" --source_model_id="/bime-munin/xiruod/llama2_SHAC/n200/Reverse-Source-set-1152-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_SHAC/n200/Weights_ReverseSource/" --quantization --gpu="2" --lambda1='1.5' --lambda2='0.5' --cpuOps

# python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_SHAC/n200/Weights_ReverseSource/set-6114-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_0.5-added.pth" --output_dir="/bime-munin/xiruod/llama2_SHAC/n200/Inferences_ReverseSource/" --quantization --gpu="2" --device="cuda:0" --batch_size=8 --cpuOps --dataset="SHAC"
# python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_SHAC/n200/Weights_ReverseSource/set-11063-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_0.5-added.pth" --output_dir="/bime-munin/xiruod/llama2_SHAC/n200/Inferences_ReverseSource/" --quantization --gpu="2" --device="cuda:0" --batch_size=8 --cpuOps --dataset="SHAC"
# python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_SHAC/n200/Weights_ReverseSource/set-1152-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_0.5-added.pth" --output_dir="/bime-munin/xiruod/llama2_SHAC/n200/Inferences_ReverseSource/" --quantization --gpu="2" --device="cuda:0" --batch_size=8 --cpuOps --dataset="SHAC"

# python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_SHAC/n200/Inferences_ReverseSource/inference_set-6114-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_0.5-added" --output_dir="../output/tmpData/SHAC_ReverseSource/" --nRuns=5 --dataset="SHAC"
# python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_SHAC/n200/Inferences_ReverseSource/inference_set-11063-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_0.5-added" --output_dir="../output/tmpData/SHAC_ReverseSource/" --nRuns=5 --dataset="SHAC"
# python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_SHAC/n200/Inferences_ReverseSource/inference_set-1152-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_0.5-added" --output_dir="../output/tmpData/SHAC_ReverseSource/" --nRuns=5 --dataset="SHAC"




# python run_editing_weights_loraMerge_TwoSources.py --target_model_id="/bime-munin/xiruod/llama2_SHAC/n200/set-6114-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_SHAC/n200/Weights/" --quantization --gpu="0" --lambda1='3' --lambda2='1' --lambda3='1' --cpuOps
# python run_editing_weights_loraMerge_TwoSources.py --target_model_id="/bime-munin/xiruod/llama2_SHAC/n200/set-11063-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_SHAC/n200/Weights/" --quantization --gpu="0" --lambda1='3' --lambda2='1' --lambda3='1' --cpuOps
# python run_editing_weights_loraMerge_TwoSources.py --target_model_id="/bime-munin/xiruod/llama2_SHAC/n200/set-1152-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_SHAC/n200/Weights/" --quantization --gpu="0" --lambda1='3' --lambda2='1' --lambda3='1' --cpuOps

# python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_SHAC/n200/Weights/set-6114-quantization-epoch3-llama-2-7B-loraR-8-lambda1_3.0-lambda2_1.0-lambda3_1.0-added.pth" --output_dir="/bime-munin/xiruod/llama2_SHAC/n200/Inferences/" --quantization --gpu="0" --device="cuda:0" --batch_size=8 --cpuOps --dataset="SHAC"
# python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_SHAC/n200/Weights/set-11063-quantization-epoch3-llama-2-7B-loraR-8-lambda1_3.0-lambda2_1.0-lambda3_1.0-added.pth" --output_dir="/bime-munin/xiruod/llama2_SHAC/n200/Inferences/" --quantization --gpu="0" --device="cuda:0" --batch_size=8 --cpuOps --dataset="SHAC"
# python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_SHAC/n200/Weights/set-1152-quantization-epoch3-llama-2-7B-loraR-8-lambda1_3.0-lambda2_1.0-lambda3_1.0-added.pth" --output_dir="/bime-munin/xiruod/llama2_SHAC/n200/Inferences/" --quantization --gpu="0" --device="cuda:0" --batch_size=8 --cpuOps --dataset="SHAC"

# python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_SHAC/n200/Inferences/inference_set-6114-quantization-epoch3-llama-2-7B-loraR-8-lambda1_3.0-lambda2_1.0-lambda3_1.0-added" --output_dir="../output/tmpData/SHAC/" --nRuns=5 --dataset="SHAC"
# python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_SHAC/n200/Inferences/inference_set-11063-quantization-epoch3-llama-2-7B-loraR-8-lambda1_3.0-lambda2_1.0-lambda3_1.0-added" --output_dir="../output/tmpData/SHAC/" --nRuns=5 --dataset="SHAC"
# python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_SHAC/n200/Inferences/inference_set-1152-quantization-epoch3-llama-2-7B-loraR-8-lambda1_3.0-lambda2_1.0-lambda3_1.0-added" --output_dir="../output/tmpData/SHAC/" --nRuns=5 --dataset="SHAC"



# python run_editing_weights_loraMerge.py --target_model_id="/bime-munin/xiruod/llama2_SHAC/n200/set-6114-quantization-epoch3-llama-2-7B-loraR-8" --source_model_id="/bime-munin/xiruod/llama2_SHAC/n200/Reverse-Source-set-6114-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_SHAC/n200/Weights_ReverseSource/" --quantization --gpu="0" --lambda1='1.05' --lambda2='0.05' --cpuOps
# python run_editing_weights_loraMerge.py --target_model_id="/bime-munin/xiruod/llama2_SHAC/n200/set-11063-quantization-epoch3-llama-2-7B-loraR-8" --source_model_id="/bime-munin/xiruod/llama2_SHAC/n200/Reverse-Source-set-11063-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_SHAC/n200/Weights_ReverseSource/" --quantization --gpu="0" --lambda1='1.05' --lambda2='0.05' --cpuOps
# python run_editing_weights_loraMerge.py --target_model_id="/bime-munin/xiruod/llama2_SHAC/n200/set-1152-quantization-epoch3-llama-2-7B-loraR-8" --source_model_id="/bime-munin/xiruod/llama2_SHAC/n200/Reverse-Source-set-1152-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_SHAC/n200/Weights_ReverseSource/" --quantization --gpu="0" --lambda1='1.05' --lambda2='0.05' --cpuOps

# python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_SHAC/n200/Weights_ReverseSource/set-6114-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.05-lambda2_0.05-added.pth" --output_dir="/bime-munin/xiruod/llama2_SHAC/n200/Inferences_ReverseSource/" --quantization --gpu="0" --device="cuda:0" --batch_size=8 --cpuOps --dataset="SHAC"
# python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_SHAC/n200/Weights_ReverseSource/set-11063-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.05-lambda2_0.05-added.pth" --output_dir="/bime-munin/xiruod/llama2_SHAC/n200/Inferences_ReverseSource/" --quantization --gpu="0" --device="cuda:0" --batch_size=8 --cpuOps --dataset="SHAC"
# python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_SHAC/n200/Weights_ReverseSource/set-1152-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.05-lambda2_0.05-added.pth" --output_dir="/bime-munin/xiruod/llama2_SHAC/n200/Inferences_ReverseSource/" --quantization --gpu="0" --device="cuda:0" --batch_size=8 --cpuOps --dataset="SHAC"

# python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_SHAC/n200/Inferences_ReverseSource/inference_set-6114-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.05-lambda2_0.05-added" --output_dir="../output/tmpData/SHAC_ReverseSource/" --nRuns=5 --dataset="SHAC"
# python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_SHAC/n200/Inferences_ReverseSource/inference_set-11063-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.05-lambda2_0.05-added" --output_dir="../output/tmpData/SHAC_ReverseSource/" --nRuns=5 --dataset="SHAC"
# python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_SHAC/n200/Inferences_ReverseSource/inference_set-1152-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.05-lambda2_0.05-added" --output_dir="../output/tmpData/SHAC_ReverseSource/" --nRuns=5 --dataset="SHAC"





# python run_editing_weights_loraMerge.py --target_model_id="/bime-munin/xiruod/llama2_SHAC/n200/set-6114-quantization-epoch3-llama-2-7B-loraR-8" --source_model_id="/bime-munin/xiruod/llama2_SHAC/n200/Reverse-Source-set-6114-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_SHAC/n200/Weights_ReverseSource/" --quantization --gpu="0" --lambda1='1.3' --lambda2='0.3' --cpuOps
# python run_editing_weights_loraMerge.py --target_model_id="/bime-munin/xiruod/llama2_SHAC/n200/set-11063-quantization-epoch3-llama-2-7B-loraR-8" --source_model_id="/bime-munin/xiruod/llama2_SHAC/n200/Reverse-Source-set-11063-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_SHAC/n200/Weights_ReverseSource/" --quantization --gpu="0" --lambda1='1.3' --lambda2='0.3' --cpuOps
# python run_editing_weights_loraMerge.py --target_model_id="/bime-munin/xiruod/llama2_SHAC/n200/set-1152-quantization-epoch3-llama-2-7B-loraR-8" --source_model_id="/bime-munin/xiruod/llama2_SHAC/n200/Reverse-Source-set-1152-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_SHAC/n200/Weights_ReverseSource/" --quantization --gpu="0" --lambda1='1.3' --lambda2='0.3' --cpuOps

# python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_SHAC/n200/Weights_ReverseSource/set-6114-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.3-lambda2_0.3-added.pth" --output_dir="/bime-munin/xiruod/llama2_SHAC/n200/Inferences_ReverseSource/" --quantization --gpu="0" --device="cuda:0" --batch_size=8 --cpuOps --dataset="SHAC"
# python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_SHAC/n200/Weights_ReverseSource/set-11063-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.3-lambda2_0.3-added.pth" --output_dir="/bime-munin/xiruod/llama2_SHAC/n200/Inferences_ReverseSource/" --quantization --gpu="0" --device="cuda:0" --batch_size=8 --cpuOps --dataset="SHAC"
# python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_SHAC/n200/Weights_ReverseSource/set-1152-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.3-lambda2_0.3-added.pth" --output_dir="/bime-munin/xiruod/llama2_SHAC/n200/Inferences_ReverseSource/" --quantization --gpu="0" --device="cuda:0" --batch_size=8 --cpuOps --dataset="SHAC"

# python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_SHAC/n200/Inferences_ReverseSource/inference_set-6114-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.3-lambda2_0.3-added" --output_dir="../output/tmpData/SHAC_ReverseSource/" --nRuns=5 --dataset="SHAC"
# python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_SHAC/n200/Inferences_ReverseSource/inference_set-11063-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.3-lambda2_0.3-added" --output_dir="../output/tmpData/SHAC_ReverseSource/" --nRuns=5 --dataset="SHAC"
# python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_SHAC/n200/Inferences_ReverseSource/inference_set-1152-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.3-lambda2_0.3-added" --output_dir="../output/tmpData/SHAC_ReverseSource/" --nRuns=5 --dataset="SHAC"





# python run_editing_weights_loraMerge.py --target_model_id="/bime-munin/xiruod/llama2_SHAC/n200/set-6114-quantization-epoch3-llama-2-7B-loraR-8" --source_model_id="/bime-munin/xiruod/llama2_SHAC/n200/Reverse-Source-set-6114-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_SHAC/n200/Weights_ReverseSource/" --quantization --gpu="0" --lambda1='1.7' --lambda2='0.7' --cpuOps
# python run_editing_weights_loraMerge.py --target_model_id="/bime-munin/xiruod/llama2_SHAC/n200/set-11063-quantization-epoch3-llama-2-7B-loraR-8" --source_model_id="/bime-munin/xiruod/llama2_SHAC/n200/Reverse-Source-set-11063-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_SHAC/n200/Weights_ReverseSource/" --quantization --gpu="0" --lambda1='1.7' --lambda2='0.7' --cpuOps
# python run_editing_weights_loraMerge.py --target_model_id="/bime-munin/xiruod/llama2_SHAC/n200/set-1152-quantization-epoch3-llama-2-7B-loraR-8" --source_model_id="/bime-munin/xiruod/llama2_SHAC/n200/Reverse-Source-set-1152-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_SHAC/n200/Weights_ReverseSource/" --quantization --gpu="0" --lambda1='1.7' --lambda2='0.7' --cpuOps

# python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_SHAC/n200/Weights_ReverseSource/set-6114-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.7-lambda2_0.7-added.pth" --output_dir="/bime-munin/xiruod/llama2_SHAC/n200/Inferences_ReverseSource/" --quantization --gpu="0" --device="cuda:0" --batch_size=8 --cpuOps --dataset="SHAC"
# python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_SHAC/n200/Weights_ReverseSource/set-11063-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.7-lambda2_0.7-added.pth" --output_dir="/bime-munin/xiruod/llama2_SHAC/n200/Inferences_ReverseSource/" --quantization --gpu="0" --device="cuda:0" --batch_size=8 --cpuOps --dataset="SHAC"
# python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_SHAC/n200/Weights_ReverseSource/set-1152-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.7-lambda2_0.7-added.pth" --output_dir="/bime-munin/xiruod/llama2_SHAC/n200/Inferences_ReverseSource/" --quantization --gpu="0" --device="cuda:0" --batch_size=8 --cpuOps --dataset="SHAC"

# python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_SHAC/n200/Inferences_ReverseSource/inference_set-6114-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.7-lambda2_0.7-added" --output_dir="../output/tmpData/SHAC_ReverseSource/" --nRuns=5 --dataset="SHAC"
# python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_SHAC/n200/Inferences_ReverseSource/inference_set-11063-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.7-lambda2_0.7-added" --output_dir="../output/tmpData/SHAC_ReverseSource/" --nRuns=5 --dataset="SHAC"
# python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_SHAC/n200/Inferences_ReverseSource/inference_set-1152-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.7-lambda2_0.7-added" --output_dir="../output/tmpData/SHAC_ReverseSource/" --nRuns=5 --dataset="SHAC"



# python run_editing_weights_loraMerge.py --target_model_id="/bime-munin/xiruod/llama2_SHAC/n200/set-6114-quantization-epoch3-llama-2-7B-loraR-8" --source_model_id="/bime-munin/xiruod/llama2_SHAC/n200/Reverse-Source-set-6114-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_SHAC/n200/Weights_ReverseSource/" --quantization --gpu="0" --lambda1='1.1' --lambda2='0.1' --cpuOps
# python run_editing_weights_loraMerge.py --target_model_id="/bime-munin/xiruod/llama2_SHAC/n200/set-11063-quantization-epoch3-llama-2-7B-loraR-8" --source_model_id="/bime-munin/xiruod/llama2_SHAC/n200/Reverse-Source-set-11063-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_SHAC/n200/Weights_ReverseSource/" --quantization --gpu="0" --lambda1='1.1' --lambda2='0.1' --cpuOps
# python run_editing_weights_loraMerge.py --target_model_id="/bime-munin/xiruod/llama2_SHAC/n200/set-1152-quantization-epoch3-llama-2-7B-loraR-8" --source_model_id="/bime-munin/xiruod/llama2_SHAC/n200/Reverse-Source-set-1152-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_SHAC/n200/Weights_ReverseSource/" --quantization --gpu="0" --lambda1='1.1' --lambda2='0.1' --cpuOps

# python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_SHAC/n200/Weights_ReverseSource/set-6114-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.1-lambda2_0.1-added.pth" --output_dir="/bime-munin/xiruod/llama2_SHAC/n200/Inferences_ReverseSource/" --quantization --gpu="0" --device="cuda:0" --batch_size=8 --cpuOps --dataset="SHAC"
# python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_SHAC/n200/Weights_ReverseSource/set-11063-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.1-lambda2_0.1-added.pth" --output_dir="/bime-munin/xiruod/llama2_SHAC/n200/Inferences_ReverseSource/" --quantization --gpu="0" --device="cuda:0" --batch_size=8 --cpuOps --dataset="SHAC"
# python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_SHAC/n200/Weights_ReverseSource/set-1152-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.1-lambda2_0.1-added.pth" --output_dir="/bime-munin/xiruod/llama2_SHAC/n200/Inferences_ReverseSource/" --quantization --gpu="0" --device="cuda:0" --batch_size=8 --cpuOps --dataset="SHAC"

# python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_SHAC/n200/Inferences_ReverseSource/inference_set-6114-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.1-lambda2_0.1-added" --output_dir="../output/tmpData/SHAC_ReverseSource/" --nRuns=5 --dataset="SHAC"
# python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_SHAC/n200/Inferences_ReverseSource/inference_set-11063-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.1-lambda2_0.1-added" --output_dir="../output/tmpData/SHAC_ReverseSource/" --nRuns=5 --dataset="SHAC"
# python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_SHAC/n200/Inferences_ReverseSource/inference_set-1152-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.1-lambda2_0.1-added" --output_dir="../output/tmpData/SHAC_ReverseSource/" --nRuns=5 --dataset="SHAC"



# python run_editing_weights_loraMerge.py --target_model_id="/bime-munin/xiruod/llama2_SHAC/n200/set-6114-quantization-epoch3-llama-2-7B-loraR-8" --source_model_id="/bime-munin/xiruod/llama2_SHAC/n200/Reverse-Source-set-6114-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_SHAC/n200/Weights_ReverseSource/" --quantization --gpu="0" --lambda1='2' --lambda2='1' --cpuOps
# python run_editing_weights_loraMerge.py --target_model_id="/bime-munin/xiruod/llama2_SHAC/n200/set-11063-quantization-epoch3-llama-2-7B-loraR-8" --source_model_id="/bime-munin/xiruod/llama2_SHAC/n200/Reverse-Source-set-11063-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_SHAC/n200/Weights_ReverseSource/" --quantization --gpu="0" --lambda1='2' --lambda2='1' --cpuOps
# python run_editing_weights_loraMerge.py --target_model_id="/bime-munin/xiruod/llama2_SHAC/n200/set-1152-quantization-epoch3-llama-2-7B-loraR-8" --source_model_id="/bime-munin/xiruod/llama2_SHAC/n200/Reverse-Source-set-1152-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_SHAC/n200/Weights_ReverseSource/" --quantization --gpu="0" --lambda1='2' --lambda2='1' --cpuOps

python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_SHAC/n200/Weights_ReverseSource/set-6114-quantization-epoch3-llama-2-7B-loraR-8-lambda1_2.0-lambda2_1.0-added.pth" --output_dir="/bime-munin/xiruod/llama2_SHAC/n200/Inferences_ReverseSource/" --quantization --gpu="0" --device="cuda:0" --batch_size=8 --cpuOps --dataset="SHAC"
python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_SHAC/n200/Weights_ReverseSource/set-11063-quantization-epoch3-llama-2-7B-loraR-8-lambda1_2.0-lambda2_1.0-added.pth" --output_dir="/bime-munin/xiruod/llama2_SHAC/n200/Inferences_ReverseSource/" --quantization --gpu="0" --device="cuda:0" --batch_size=8 --cpuOps --dataset="SHAC"
python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_SHAC/n200/Weights_ReverseSource/set-1152-quantization-epoch3-llama-2-7B-loraR-8-lambda1_2.0-lambda2_1.0-added.pth" --output_dir="/bime-munin/xiruod/llama2_SHAC/n200/Inferences_ReverseSource/" --quantization --gpu="0" --device="cuda:0" --batch_size=8 --cpuOps --dataset="SHAC"

python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_SHAC/n200/Inferences_ReverseSource/inference_set-6114-quantization-epoch3-llama-2-7B-loraR-8-lambda1_2.0-lambda2_1.0-added" --output_dir="../output/tmpData/SHAC_ReverseSource/" --nRuns=5 --dataset="SHAC"
python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_SHAC/n200/Inferences_ReverseSource/inference_set-11063-quantization-epoch3-llama-2-7B-loraR-8-lambda1_2.0-lambda2_1.0-added" --output_dir="../output/tmpData/SHAC_ReverseSource/" --nRuns=5 --dataset="SHAC"
python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_SHAC/n200/Inferences_ReverseSource/inference_set-1152-quantization-epoch3-llama-2-7B-loraR-8-lambda1_2.0-lambda2_1.0-added" --output_dir="../output/tmpData/SHAC_ReverseSource/" --nRuns=5 --dataset="SHAC"



# python run_editing_weights_loraMerge_TwoSources.py --target_model_id="/bime-munin/xiruod/llama2_SHAC/n200/set-6114-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_SHAC/n200/Weights/" --quantization --gpu="0" --lambda1='2' --lambda2='0.5' --lambda3='0.5' --cpuOps
# python run_editing_weights_loraMerge_TwoSources.py --target_model_id="/bime-munin/xiruod/llama2_SHAC/n200/set-11063-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_SHAC/n200/Weights/" --quantization --gpu="0" --lambda1='2' --lambda2='0.5' --lambda3='0.5' --cpuOps
# python run_editing_weights_loraMerge_TwoSources.py --target_model_id="/bime-munin/xiruod/llama2_SHAC/n200/set-1152-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_SHAC/n200/Weights/" --quantization --gpu="0" --lambda1='2' --lambda2='0.5' --lambda3='0.5' --cpuOps

# python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_SHAC/n200/Weights/set-6114-quantization-epoch3-llama-2-7B-loraR-8-lambda1_2.0-lambda2_0.5-lambda3_0.5-added.pth" --output_dir="/bime-munin/xiruod/llama2_SHAC/n200/Inferences/" --quantization --gpu="0" --device="cuda:0" --batch_size=8 --cpuOps --dataset="SHAC"
# python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_SHAC/n200/Weights/set-11063-quantization-epoch3-llama-2-7B-loraR-8-lambda1_2.0-lambda2_0.5-lambda3_0.5-added.pth" --output_dir="/bime-munin/xiruod/llama2_SHAC/n200/Inferences/" --quantization --gpu="0" --device="cuda:0" --batch_size=8 --cpuOps --dataset="SHAC"
# python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_SHAC/n200/Weights/set-1152-quantization-epoch3-llama-2-7B-loraR-8-lambda1_2.0-lambda2_0.5-lambda3_0.5-added.pth" --output_dir="/bime-munin/xiruod/llama2_SHAC/n200/Inferences/" --quantization --gpu="0" --device="cuda:0" --batch_size=8 --cpuOps --dataset="SHAC"

# python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_SHAC/n200/Inferences/inference_set-6114-quantization-epoch3-llama-2-7B-loraR-8-lambda1_2.0-lambda2_0.5-lambda3_0.5-added" --output_dir="../output/tmpData/SHAC/" --nRuns=5 --dataset="SHAC"
# python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_SHAC/n200/Inferences/inference_set-11063-quantization-epoch3-llama-2-7B-loraR-8-lambda1_2.0-lambda2_0.5-lambda3_0.5-added" --output_dir="../output/tmpData/SHAC/" --nRuns=5 --dataset="SHAC"
# python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_SHAC/n200/Inferences/inference_set-1152-quantization-epoch3-llama-2-7B-loraR-8-lambda1_2.0-lambda2_0.5-lambda3_0.5-added" --output_dir="../output/tmpData/SHAC/" --nRuns=5 --dataset="SHAC"



# python run_editing_weights_loraMerge_TwoSources.py --target_model_id="/bime-munin/xiruod/llama2_SHAC/n200/set-6114-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_SHAC/n200/Weights/" --quantization --gpu="0" --lambda1='1.6' --lambda2='0.3' --lambda3='0.3' --cpuOps
# python run_editing_weights_loraMerge_TwoSources.py --target_model_id="/bime-munin/xiruod/llama2_SHAC/n200/set-11063-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_SHAC/n200/Weights/" --quantization --gpu="0" --lambda1='1.6' --lambda2='0.3' --lambda3='0.3' --cpuOps
# python run_editing_weights_loraMerge_TwoSources.py --target_model_id="/bime-munin/xiruod/llama2_SHAC/n200/set-1152-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_SHAC/n200/Weights/" --quantization --gpu="0" --lambda1='1.6' --lambda2='0.3' --lambda3='0.3' --cpuOps

# python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_SHAC/n200/Weights/set-6114-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.6-lambda2_0.3-lambda3_0.3-added.pth" --output_dir="/bime-munin/xiruod/llama2_SHAC/n200/Inferences/" --quantization --gpu="0" --device="cuda:0" --batch_size=8 --cpuOps --dataset="SHAC"
# python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_SHAC/n200/Weights/set-11063-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.6-lambda2_0.3-lambda3_0.3-added.pth" --output_dir="/bime-munin/xiruod/llama2_SHAC/n200/Inferences/" --quantization --gpu="0" --device="cuda:0" --batch_size=8 --cpuOps --dataset="SHAC"
# python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_SHAC/n200/Weights/set-1152-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.6-lambda2_0.3-lambda3_0.3-added.pth" --output_dir="/bime-munin/xiruod/llama2_SHAC/n200/Inferences/" --quantization --gpu="0" --device="cuda:0" --batch_size=8 --cpuOps --dataset="SHAC"

# python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_SHAC/n200/Inferences/inference_set-6114-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.6-lambda2_0.3-lambda3_0.3-added" --output_dir="../output/tmpData/SHAC/" --nRuns=5 --dataset="SHAC"
# python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_SHAC/n200/Inferences/inference_set-11063-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.6-lambda2_0.3-lambda3_0.3-added" --output_dir="../output/tmpData/SHAC/" --nRuns=5 --dataset="SHAC"
# python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_SHAC/n200/Inferences/inference_set-1152-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.6-lambda2_0.3-lambda3_0.3-added" --output_dir="../output/tmpData/SHAC/" --nRuns=5 --dataset="SHAC"



# python run_editing_weights_loraMerge_TwoSources.py --target_model_id="/bime-munin/xiruod/llama2_SHAC/n200/set-6114-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_SHAC/n200/Weights/" --quantization --gpu="0" --lambda1='2.6' --lambda2='0.8' --lambda3='0.8' --cpuOps
# python run_editing_weights_loraMerge_TwoSources.py --target_model_id="/bime-munin/xiruod/llama2_SHAC/n200/set-11063-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_SHAC/n200/Weights/" --quantization --gpu="0" --lambda1='2.6' --lambda2='0.8' --lambda3='0.8' --cpuOps
# python run_editing_weights_loraMerge_TwoSources.py --target_model_id="/bime-munin/xiruod/llama2_SHAC/n200/set-1152-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_SHAC/n200/Weights/" --quantization --gpu="0" --lambda1='2.6' --lambda2='0.8' --lambda3='0.8' --cpuOps

# python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_SHAC/n200/Weights/set-6114-quantization-epoch3-llama-2-7B-loraR-8-lambda1_2.6-lambda2_0.8-lambda3_0.8-added.pth" --output_dir="/bime-munin/xiruod/llama2_SHAC/n200/Inferences/" --quantization --gpu="0" --device="cuda:0" --batch_size=8 --cpuOps --dataset="SHAC"
# python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_SHAC/n200/Weights/set-11063-quantization-epoch3-llama-2-7B-loraR-8-lambda1_2.6-lambda2_0.8-lambda3_0.8-added.pth" --output_dir="/bime-munin/xiruod/llama2_SHAC/n200/Inferences/" --quantization --gpu="0" --device="cuda:0" --batch_size=8 --cpuOps --dataset="SHAC"
# python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_SHAC/n200/Weights/set-1152-quantization-epoch3-llama-2-7B-loraR-8-lambda1_2.6-lambda2_0.8-lambda3_0.8-added.pth" --output_dir="/bime-munin/xiruod/llama2_SHAC/n200/Inferences/" --quantization --gpu="0" --device="cuda:0" --batch_size=8 --cpuOps --dataset="SHAC"

# python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_SHAC/n200/Inferences/inference_set-6114-quantization-epoch3-llama-2-7B-loraR-8-lambda1_2.6-lambda2_0.8-lambda3_0.8-added" --output_dir="../output/tmpData/SHAC/" --nRuns=5 --dataset="SHAC"
# python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_SHAC/n200/Inferences/inference_set-11063-quantization-epoch3-llama-2-7B-loraR-8-lambda1_2.6-lambda2_0.8-lambda3_0.8-added" --output_dir="../output/tmpData/SHAC/" --nRuns=5 --dataset="SHAC"
# python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_SHAC/n200/Inferences/inference_set-1152-quantization-epoch3-llama-2-7B-loraR-8-lambda1_2.6-lambda2_0.8-lambda3_0.8-added" --output_dir="../output/tmpData/SHAC/" --nRuns=5 --dataset="SHAC"


# python run_editing_weights_loraMerge_TwoSources.py --target_model_id="/bime-munin/xiruod/llama2_SHAC/n200/set-6114-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_SHAC/n200/Weights/" --quantization --gpu="0" --lambda1='1' --lambda2='0' --lambda3='0' --cpuOps
# python run_editing_weights_loraMerge_TwoSources.py --target_model_id="/bime-munin/xiruod/llama2_SHAC/n200/set-11063-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_SHAC/n200/Weights/" --quantization --gpu="0" --lambda1='1' --lambda2='0' --lambda3='0' --cpuOps
# python run_editing_weights_loraMerge_TwoSources.py --target_model_id="/bime-munin/xiruod/llama2_SHAC/n200/set-1152-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_SHAC/n200/Weights/" --quantization --gpu="0" --lambda1='1' --lambda2='0' --lambda3='0' --cpuOps

# python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_SHAC/n200/Weights/set-6114-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.0-lambda2_0.0-lambda3_0.0-added.pth" --output_dir="/bime-munin/xiruod/llama2_SHAC/n200/Inferences/" --quantization --gpu="0" --device="cuda:0" --batch_size=8 --cpuOps --dataset="SHAC"
# python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_SHAC/n200/Weights/set-11063-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.0-lambda2_0.0-lambda3_0.0-added.pth" --output_dir="/bime-munin/xiruod/llama2_SHAC/n200/Inferences/" --quantization --gpu="0" --device="cuda:0" --batch_size=8 --cpuOps --dataset="SHAC"
# python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_SHAC/n200/Weights/set-1152-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.0-lambda2_0.0-lambda3_0.0-added.pth" --output_dir="/bime-munin/xiruod/llama2_SHAC/n200/Inferences/" --quantization --gpu="0" --device="cuda:0" --batch_size=8 --cpuOps --dataset="SHAC"

# python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_SHAC/n200/Inferences/inference_set-6114-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.0-lambda2_0.0-lambda3_0.0-added" --output_dir="../output/tmpData/SHAC/" --nRuns=5 --dataset="SHAC"
# python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_SHAC/n200/Inferences/inference_set-11063-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.0-lambda2_0.0-lambda3_0.0-added" --output_dir="../output/tmpData/SHAC/" --nRuns=5 --dataset="SHAC"
# python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_SHAC/n200/Inferences/inference_set-1152-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.0-lambda2_0.0-lambda3_0.0-added" --output_dir="../output/tmpData/SHAC/" --nRuns=5 --dataset="SHAC"