
### CD: 1.5 Exp. One Side (RS) = 6621
python run_editing_weights_loraMerge.py --target_model_id="/bime-munin/xiruod/llama2_CD/n200/set-6621-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_CD/n200/Weights_ReverseSource/" --source_model_id="/bime-munin/xiruod/llama2_CD/n200/Reverse-Source-set-6621-quantization-epoch3-llama-2-7B-loraR-8"  --quantization --gpu="1" --lambda1='1.5' --lambda2='0.0' --cpuOps
python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_CD/n200/Weights_ReverseSource/set-6621-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_0.0-added.pth" --output_dir="/bime-munin/xiruod/llama2_CD/n200/Inferences_ReverseSource/" --quantization --gpu="1" --device="cuda:0" --batch_size=8 --cpuOps --dataset="CD"
python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_CD/n200/Inferences_ReverseSource/inference_set-6621-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_0.0-added" --output_dir="../output/tmpData/CD_ReverseSource/" --nRuns=5 --dataset="CD"


python run_editing_weights_loraMerge.py --target_model_id="/bime-munin/xiruod/llama2_CD/n200/set-6621-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_CD/n200/Weights_ReverseSource/" --source_model_id="/bime-munin/xiruod/llama2_CD/n200/Reverse-Source-set-6621-quantization-epoch3-llama-2-7B-loraR-8"  --quantization --gpu="1" --lambda1='1.5' --lambda2='0.25' --cpuOps
python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_CD/n200/Weights_ReverseSource/set-6621-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_0.25-added.pth" --output_dir="/bime-munin/xiruod/llama2_CD/n200/Inferences_ReverseSource/" --quantization --gpu="1" --device="cuda:0" --batch_size=8 --cpuOps --dataset="CD"
python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_CD/n200/Inferences_ReverseSource/inference_set-6621-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_0.25-added" --output_dir="../output/tmpData/CD_ReverseSource/" --nRuns=5 --dataset="CD"

python run_editing_weights_loraMerge.py --target_model_id="/bime-munin/xiruod/llama2_CD/n200/set-6621-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_CD/n200/Weights_ReverseSource/" --source_model_id="/bime-munin/xiruod/llama2_CD/n200/Reverse-Source-set-6621-quantization-epoch3-llama-2-7B-loraR-8"  --quantization --gpu="1" --lambda1='1.5' --lambda2='0.5' --cpuOps
python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_CD/n200/Weights_ReverseSource/set-6621-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_0.5-added.pth" --output_dir="/bime-munin/xiruod/llama2_CD/n200/Inferences_ReverseSource/" --quantization --gpu="1" --device="cuda:0" --batch_size=8 --cpuOps --dataset="CD"
python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_CD/n200/Inferences_ReverseSource/inference_set-6621-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_0.5-added" --output_dir="../output/tmpData/CD_ReverseSource/" --nRuns=5 --dataset="CD"

python run_editing_weights_loraMerge.py --target_model_id="/bime-munin/xiruod/llama2_CD/n200/set-6621-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_CD/n200/Weights_ReverseSource/" --source_model_id="/bime-munin/xiruod/llama2_CD/n200/Reverse-Source-set-6621-quantization-epoch3-llama-2-7B-loraR-8"  --quantization --gpu="1" --lambda1='1.5' --lambda2='0.75' --cpuOps
python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_CD/n200/Weights_ReverseSource/set-6621-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_0.75-added.pth" --output_dir="/bime-munin/xiruod/llama2_CD/n200/Inferences_ReverseSource/" --quantization --gpu="1" --device="cuda:0" --batch_size=8 --cpuOps --dataset="CD"
python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_CD/n200/Inferences_ReverseSource/inference_set-6621-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_0.75-added" --output_dir="../output/tmpData/CD_ReverseSource/" --nRuns=5 --dataset="CD"

python run_editing_weights_loraMerge.py --target_model_id="/bime-munin/xiruod/llama2_CD/n200/set-6621-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_CD/n200/Weights_ReverseSource/" --source_model_id="/bime-munin/xiruod/llama2_CD/n200/Reverse-Source-set-6621-quantization-epoch3-llama-2-7B-loraR-8"  --quantization --gpu="1" --lambda1='1.5' --lambda2='1.0' --cpuOps
python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_CD/n200/Weights_ReverseSource/set-6621-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_1.0-added.pth" --output_dir="/bime-munin/xiruod/llama2_CD/n200/Inferences_ReverseSource/" --quantization --gpu="1" --device="cuda:0" --batch_size=8 --cpuOps --dataset="CD"
python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_CD/n200/Inferences_ReverseSource/inference_set-6621-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_1.0-added" --output_dir="../output/tmpData/CD_ReverseSource/" --nRuns=5 --dataset="CD"

python run_editing_weights_loraMerge.py --target_model_id="/bime-munin/xiruod/llama2_CD/n200/set-6621-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_CD/n200/Weights_ReverseSource/" --source_model_id="/bime-munin/xiruod/llama2_CD/n200/Reverse-Source-set-6621-quantization-epoch3-llama-2-7B-loraR-8"  --quantization --gpu="1" --lambda1='1.5' --lambda2='1.25' --cpuOps
python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_CD/n200/Weights_ReverseSource/set-6621-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_1.25-added.pth" --output_dir="/bime-munin/xiruod/llama2_CD/n200/Inferences_ReverseSource/" --quantization --gpu="1" --device="cuda:0" --batch_size=8 --cpuOps --dataset="CD"
python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_CD/n200/Inferences_ReverseSource/inference_set-6621-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_1.25-added" --output_dir="../output/tmpData/CD_ReverseSource/" --nRuns=5 --dataset="CD"

python run_editing_weights_loraMerge.py --target_model_id="/bime-munin/xiruod/llama2_CD/n200/set-6621-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_CD/n200/Weights_ReverseSource/" --source_model_id="/bime-munin/xiruod/llama2_CD/n200/Reverse-Source-set-6621-quantization-epoch3-llama-2-7B-loraR-8"  --quantization --gpu="1" --lambda1='1.5' --lambda2='1.5' --cpuOps
python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_CD/n200/Weights_ReverseSource/set-6621-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_1.5-added.pth" --output_dir="/bime-munin/xiruod/llama2_CD/n200/Inferences_ReverseSource/" --quantization --gpu="1" --device="cuda:0" --batch_size=8 --cpuOps --dataset="CD"
python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_CD/n200/Inferences_ReverseSource/inference_set-6621-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_1.5-added" --output_dir="../output/tmpData/CD_ReverseSource/" --nRuns=5 --dataset="CD"

python run_editing_weights_loraMerge.py --target_model_id="/bime-munin/xiruod/llama2_CD/n200/set-6621-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_CD/n200/Weights_ReverseSource/" --source_model_id="/bime-munin/xiruod/llama2_CD/n200/Reverse-Source-set-6621-quantization-epoch3-llama-2-7B-loraR-8"  --quantization --gpu="1" --lambda1='1.5' --lambda2='1.75' --cpuOps
python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_CD/n200/Weights_ReverseSource/set-6621-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_1.75-added.pth" --output_dir="/bime-munin/xiruod/llama2_CD/n200/Inferences_ReverseSource/" --quantization --gpu="1" --device="cuda:0" --batch_size=8 --cpuOps --dataset="CD"
python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_CD/n200/Inferences_ReverseSource/inference_set-6621-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_1.75-added" --output_dir="../output/tmpData/CD_ReverseSource/" --nRuns=5 --dataset="CD"

python run_editing_weights_loraMerge.py --target_model_id="/bime-munin/xiruod/llama2_CD/n200/set-6621-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_CD/n200/Weights_ReverseSource/" --source_model_id="/bime-munin/xiruod/llama2_CD/n200/Reverse-Source-set-6621-quantization-epoch3-llama-2-7B-loraR-8"  --quantization --gpu="1" --lambda1='1.5' --lambda2='2.0' --cpuOps
python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_CD/n200/Weights_ReverseSource/set-6621-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_2.0-added.pth" --output_dir="/bime-munin/xiruod/llama2_CD/n200/Inferences_ReverseSource/" --quantization --gpu="1" --device="cuda:0" --batch_size=8 --cpuOps --dataset="CD"
python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_CD/n200/Inferences_ReverseSource/inference_set-6621-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_2.0-added" --output_dir="../output/tmpData/CD_ReverseSource/" --nRuns=5 --dataset="CD"


python run_editing_weights_loraMerge.py --target_model_id="/bime-munin/xiruod/llama2_CD/n200/set-6621-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_CD/n200/Weights_ReverseSource/" --source_model_id="/bime-munin/xiruod/llama2_CD/n200/Reverse-Source-set-6621-quantization-epoch3-llama-2-7B-loraR-8"  --quantization --gpu="1" --lambda1='1.5' --lambda2='2.5' --cpuOps
python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_CD/n200/Weights_ReverseSource/set-6621-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_2.5-added.pth" --output_dir="/bime-munin/xiruod/llama2_CD/n200/Inferences_ReverseSource/" --quantization --gpu="1" --device="cuda:0" --batch_size=8 --cpuOps --dataset="CD"
python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_CD/n200/Inferences_ReverseSource/inference_set-6621-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_2.5-added" --output_dir="../output/tmpData/CD_ReverseSource/" --nRuns=5 --dataset="CD"

python run_editing_weights_loraMerge.py --target_model_id="/bime-munin/xiruod/llama2_CD/n200/set-6621-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_CD/n200/Weights_ReverseSource/" --source_model_id="/bime-munin/xiruod/llama2_CD/n200/Reverse-Source-set-6621-quantization-epoch3-llama-2-7B-loraR-8"  --quantization --gpu="1" --lambda1='1.5' --lambda2='3.0' --cpuOps
python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_CD/n200/Weights_ReverseSource/set-6621-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_3.0-added.pth" --output_dir="/bime-munin/xiruod/llama2_CD/n200/Inferences_ReverseSource/" --quantization --gpu="1" --device="cuda:0" --batch_size=8 --cpuOps --dataset="CD"
python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_CD/n200/Inferences_ReverseSource/inference_set-6621-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_3.0-added" --output_dir="../output/tmpData/CD_ReverseSource/" --nRuns=5 --dataset="CD"

#######
### CD: 1.5 Exp. One Side (RS) = 566
python run_editing_weights_loraMerge.py --target_model_id="/bime-munin/xiruod/llama2_CD/n200/set-566-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_CD/n200/Weights_ReverseSource/" --source_model_id="/bime-munin/xiruod/llama2_CD/n200/Reverse-Source-set-566-quantization-epoch3-llama-2-7B-loraR-8" --quantization --gpu="1" --lambda1='1.5' --lambda2='0.0' --cpuOps
python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_CD/n200/Weights_ReverseSource/set-566-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_0.0-added.pth" --output_dir="/bime-munin/xiruod/llama2_CD/n200/Inferences_ReverseSource/" --quantization --gpu="1" --device="cuda:0" --batch_size=8 --cpuOps --dataset="CD"
python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_CD/n200/Inferences_ReverseSource/inference_set-566-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_0.0-added" --output_dir="../output/tmpData/CD_ReverseSource/" --nRuns=5 --dataset="CD"


python run_editing_weights_loraMerge.py --target_model_id="/bime-munin/xiruod/llama2_CD/n200/set-566-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_CD/n200/Weights_ReverseSource/" --source_model_id="/bime-munin/xiruod/llama2_CD/n200/Reverse-Source-set-566-quantization-epoch3-llama-2-7B-loraR-8" --quantization --gpu="1" --lambda1='1.5' --lambda2='0.25' --cpuOps
python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_CD/n200/Weights_ReverseSource/set-566-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_0.25-added.pth" --output_dir="/bime-munin/xiruod/llama2_CD/n200/Inferences_ReverseSource/" --quantization --gpu="1" --device="cuda:0" --batch_size=8 --cpuOps --dataset="CD"
python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_CD/n200/Inferences_ReverseSource/inference_set-566-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_0.25-added" --output_dir="../output/tmpData/CD_ReverseSource/" --nRuns=5 --dataset="CD"

python run_editing_weights_loraMerge.py --target_model_id="/bime-munin/xiruod/llama2_CD/n200/set-566-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_CD/n200/Weights_ReverseSource/" --source_model_id="/bime-munin/xiruod/llama2_CD/n200/Reverse-Source-set-566-quantization-epoch3-llama-2-7B-loraR-8" --quantization --gpu="1" --lambda1='1.5' --lambda2='0.5' --cpuOps
python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_CD/n200/Weights_ReverseSource/set-566-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_0.5-added.pth" --output_dir="/bime-munin/xiruod/llama2_CD/n200/Inferences_ReverseSource/" --quantization --gpu="1" --device="cuda:0" --batch_size=8 --cpuOps --dataset="CD"
python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_CD/n200/Inferences_ReverseSource/inference_set-566-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_0.5-added" --output_dir="../output/tmpData/CD_ReverseSource/" --nRuns=5 --dataset="CD"

python run_editing_weights_loraMerge.py --target_model_id="/bime-munin/xiruod/llama2_CD/n200/set-566-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_CD/n200/Weights_ReverseSource/" --source_model_id="/bime-munin/xiruod/llama2_CD/n200/Reverse-Source-set-566-quantization-epoch3-llama-2-7B-loraR-8" --quantization --gpu="1" --lambda1='1.5' --lambda2='0.75' --cpuOps
python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_CD/n200/Weights_ReverseSource/set-566-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_0.75-added.pth" --output_dir="/bime-munin/xiruod/llama2_CD/n200/Inferences_ReverseSource/" --quantization --gpu="1" --device="cuda:0" --batch_size=8 --cpuOps --dataset="CD"
python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_CD/n200/Inferences_ReverseSource/inference_set-566-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_0.75-added" --output_dir="../output/tmpData/CD_ReverseSource/" --nRuns=5 --dataset="CD"

python run_editing_weights_loraMerge.py --target_model_id="/bime-munin/xiruod/llama2_CD/n200/set-566-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_CD/n200/Weights_ReverseSource/" --source_model_id="/bime-munin/xiruod/llama2_CD/n200/Reverse-Source-set-566-quantization-epoch3-llama-2-7B-loraR-8" --quantization --gpu="1" --lambda1='1.5' --lambda2='1.0' --cpuOps
python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_CD/n200/Weights_ReverseSource/set-566-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_1.0-added.pth" --output_dir="/bime-munin/xiruod/llama2_CD/n200/Inferences_ReverseSource/" --quantization --gpu="1" --device="cuda:0" --batch_size=8 --cpuOps --dataset="CD"
python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_CD/n200/Inferences_ReverseSource/inference_set-566-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_1.0-added" --output_dir="../output/tmpData/CD_ReverseSource/" --nRuns=5 --dataset="CD"

python run_editing_weights_loraMerge.py --target_model_id="/bime-munin/xiruod/llama2_CD/n200/set-566-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_CD/n200/Weights_ReverseSource/" --source_model_id="/bime-munin/xiruod/llama2_CD/n200/Reverse-Source-set-566-quantization-epoch3-llama-2-7B-loraR-8" --quantization --gpu="1" --lambda1='1.5' --lambda2='1.25' --cpuOps
python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_CD/n200/Weights_ReverseSource/set-566-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_1.25-added.pth" --output_dir="/bime-munin/xiruod/llama2_CD/n200/Inferences_ReverseSource/" --quantization --gpu="1" --device="cuda:0" --batch_size=8 --cpuOps --dataset="CD"
python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_CD/n200/Inferences_ReverseSource/inference_set-566-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_1.25-added" --output_dir="../output/tmpData/CD_ReverseSource/" --nRuns=5 --dataset="CD"

python run_editing_weights_loraMerge.py --target_model_id="/bime-munin/xiruod/llama2_CD/n200/set-566-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_CD/n200/Weights_ReverseSource/" --source_model_id="/bime-munin/xiruod/llama2_CD/n200/Reverse-Source-set-566-quantization-epoch3-llama-2-7B-loraR-8" --quantization --gpu="1" --lambda1='1.5' --lambda2='1.5' --cpuOps
python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_CD/n200/Weights_ReverseSource/set-566-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_1.5-added.pth" --output_dir="/bime-munin/xiruod/llama2_CD/n200/Inferences_ReverseSource/" --quantization --gpu="1" --device="cuda:0" --batch_size=8 --cpuOps --dataset="CD"
python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_CD/n200/Inferences_ReverseSource/inference_set-566-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_1.5-added" --output_dir="../output/tmpData/CD_ReverseSource/" --nRuns=5 --dataset="CD"

python run_editing_weights_loraMerge.py --target_model_id="/bime-munin/xiruod/llama2_CD/n200/set-566-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_CD/n200/Weights_ReverseSource/" --source_model_id="/bime-munin/xiruod/llama2_CD/n200/Reverse-Source-set-566-quantization-epoch3-llama-2-7B-loraR-8" --quantization --gpu="1" --lambda1='1.5' --lambda2='1.75' --cpuOps
python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_CD/n200/Weights_ReverseSource/set-566-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_1.75-added.pth" --output_dir="/bime-munin/xiruod/llama2_CD/n200/Inferences_ReverseSource/" --quantization --gpu="1" --device="cuda:0" --batch_size=8 --cpuOps --dataset="CD"
python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_CD/n200/Inferences_ReverseSource/inference_set-566-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_1.75-added" --output_dir="../output/tmpData/CD_ReverseSource/" --nRuns=5 --dataset="CD"

python run_editing_weights_loraMerge.py --target_model_id="/bime-munin/xiruod/llama2_CD/n200/set-566-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_CD/n200/Weights_ReverseSource/" --source_model_id="/bime-munin/xiruod/llama2_CD/n200/Reverse-Source-set-566-quantization-epoch3-llama-2-7B-loraR-8" --quantization --gpu="1" --lambda1='1.5' --lambda2='2.0' --cpuOps
python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_CD/n200/Weights_ReverseSource/set-566-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_2.0-added.pth" --output_dir="/bime-munin/xiruod/llama2_CD/n200/Inferences_ReverseSource/" --quantization --gpu="1" --device="cuda:0" --batch_size=8 --cpuOps --dataset="CD"
python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_CD/n200/Inferences_ReverseSource/inference_set-566-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_2.0-added" --output_dir="../output/tmpData/CD_ReverseSource/" --nRuns=5 --dataset="CD"



python run_editing_weights_loraMerge.py --target_model_id="/bime-munin/xiruod/llama2_CD/n200/set-566-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_CD/n200/Weights_ReverseSource/" --source_model_id="/bime-munin/xiruod/llama2_CD/n200/Reverse-Source-set-566-quantization-epoch3-llama-2-7B-loraR-8" --quantization --gpu="1" --lambda1='1.5' --lambda2='2.5' --cpuOps
python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_CD/n200/Weights_ReverseSource/set-566-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_2.5-added.pth" --output_dir="/bime-munin/xiruod/llama2_CD/n200/Inferences_ReverseSource/" --quantization --gpu="1" --device="cuda:0" --batch_size=8 --cpuOps --dataset="CD"
python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_CD/n200/Inferences_ReverseSource/inference_set-566-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_2.5-added" --output_dir="../output/tmpData/CD_ReverseSource/" --nRuns=5 --dataset="CD"


python run_editing_weights_loraMerge.py --target_model_id="/bime-munin/xiruod/llama2_CD/n200/set-566-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_CD/n200/Weights_ReverseSource/" --source_model_id="/bime-munin/xiruod/llama2_CD/n200/Reverse-Source-set-566-quantization-epoch3-llama-2-7B-loraR-8" --quantization --gpu="1" --lambda1='1.5' --lambda2='3.0' --cpuOps
python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_CD/n200/Weights_ReverseSource/set-566-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_3.0-added.pth" --output_dir="/bime-munin/xiruod/llama2_CD/n200/Inferences_ReverseSource/" --quantization --gpu="1" --device="cuda:0" --batch_size=8 --cpuOps --dataset="CD"
python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_CD/n200/Inferences_ReverseSource/inference_set-566-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_3.0-added" --output_dir="../output/tmpData/CD_ReverseSource/" --nRuns=5 --dataset="CD"


### CD: 1.5 Exp. One Side (RS) = 3636
python run_editing_weights_loraMerge.py --target_model_id="/bime-munin/xiruod/llama2_CD/n200/set-3636-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_CD/n200/Weights_ReverseSource/" --source_model_id="/bime-munin/xiruod/llama2_CD/n200/Reverse-Source-set-3636-quantization-epoch3-llama-2-7B-loraR-8" --quantization --gpu="1" --lambda1='1.5' --lambda2='0.0' --cpuOps
python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_CD/n200/Weights_ReverseSource/set-3636-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_0.0-added.pth" --output_dir="/bime-munin/xiruod/llama2_CD/n200/Inferences_ReverseSource/" --quantization --gpu="1" --device="cuda:0" --batch_size=8 --cpuOps --dataset="CD"
python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_CD/n200/Inferences_ReverseSource/inference_set-3636-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_0.0-added" --output_dir="../output/tmpData/CD_ReverseSource/" --nRuns=5 --dataset="CD"


python run_editing_weights_loraMerge.py --target_model_id="/bime-munin/xiruod/llama2_CD/n200/set-3636-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_CD/n200/Weights_ReverseSource/" --source_model_id="/bime-munin/xiruod/llama2_CD/n200/Reverse-Source-set-3636-quantization-epoch3-llama-2-7B-loraR-8" --quantization --gpu="1" --lambda1='1.5' --lambda2='0.25' --cpuOps
python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_CD/n200/Weights_ReverseSource/set-3636-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_0.25-added.pth" --output_dir="/bime-munin/xiruod/llama2_CD/n200/Inferences_ReverseSource/" --quantization --gpu="1" --device="cuda:0" --batch_size=8 --cpuOps --dataset="CD"
python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_CD/n200/Inferences_ReverseSource/inference_set-3636-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_0.25-added" --output_dir="../output/tmpData/CD_ReverseSource/" --nRuns=5 --dataset="CD"

python run_editing_weights_loraMerge.py --target_model_id="/bime-munin/xiruod/llama2_CD/n200/set-3636-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_CD/n200/Weights_ReverseSource/" --source_model_id="/bime-munin/xiruod/llama2_CD/n200/Reverse-Source-set-3636-quantization-epoch3-llama-2-7B-loraR-8" --quantization --gpu="1" --lambda1='1.5' --lambda2='0.5' --cpuOps
python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_CD/n200/Weights_ReverseSource/set-3636-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_0.5-added.pth" --output_dir="/bime-munin/xiruod/llama2_CD/n200/Inferences_ReverseSource/" --quantization --gpu="1" --device="cuda:0" --batch_size=8 --cpuOps --dataset="CD"
python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_CD/n200/Inferences_ReverseSource/inference_set-3636-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_0.5-added" --output_dir="../output/tmpData/CD_ReverseSource/" --nRuns=5 --dataset="CD"

python run_editing_weights_loraMerge.py --target_model_id="/bime-munin/xiruod/llama2_CD/n200/set-3636-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_CD/n200/Weights_ReverseSource/" --source_model_id="/bime-munin/xiruod/llama2_CD/n200/Reverse-Source-set-3636-quantization-epoch3-llama-2-7B-loraR-8" --quantization --gpu="1" --lambda1='1.5' --lambda2='0.75' --cpuOps
python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_CD/n200/Weights_ReverseSource/set-3636-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_0.75-added.pth" --output_dir="/bime-munin/xiruod/llama2_CD/n200/Inferences_ReverseSource/" --quantization --gpu="1" --device="cuda:0" --batch_size=8 --cpuOps --dataset="CD"
python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_CD/n200/Inferences_ReverseSource/inference_set-3636-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_0.75-added" --output_dir="../output/tmpData/CD_ReverseSource/" --nRuns=5 --dataset="CD"

python run_editing_weights_loraMerge.py --target_model_id="/bime-munin/xiruod/llama2_CD/n200/set-3636-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_CD/n200/Weights_ReverseSource/" --source_model_id="/bime-munin/xiruod/llama2_CD/n200/Reverse-Source-set-3636-quantization-epoch3-llama-2-7B-loraR-8" --quantization --gpu="1" --lambda1='1.5' --lambda2='1.0' --cpuOps
python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_CD/n200/Weights_ReverseSource/set-3636-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_1.0-added.pth" --output_dir="/bime-munin/xiruod/llama2_CD/n200/Inferences_ReverseSource/" --quantization --gpu="1" --device="cuda:0" --batch_size=8 --cpuOps --dataset="CD"
python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_CD/n200/Inferences_ReverseSource/inference_set-3636-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_1.0-added" --output_dir="../output/tmpData/CD_ReverseSource/" --nRuns=5 --dataset="CD"

python run_editing_weights_loraMerge.py --target_model_id="/bime-munin/xiruod/llama2_CD/n200/set-3636-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_CD/n200/Weights_ReverseSource/" --source_model_id="/bime-munin/xiruod/llama2_CD/n200/Reverse-Source-set-3636-quantization-epoch3-llama-2-7B-loraR-8" --quantization --gpu="1" --lambda1='1.5' --lambda2='1.25' --cpuOps
python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_CD/n200/Weights_ReverseSource/set-3636-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_1.25-added.pth" --output_dir="/bime-munin/xiruod/llama2_CD/n200/Inferences_ReverseSource/" --quantization --gpu="1" --device="cuda:0" --batch_size=8 --cpuOps --dataset="CD"
python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_CD/n200/Inferences_ReverseSource/inference_set-3636-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_1.25-added" --output_dir="../output/tmpData/CD_ReverseSource/" --nRuns=5 --dataset="CD"

python run_editing_weights_loraMerge.py --target_model_id="/bime-munin/xiruod/llama2_CD/n200/set-3636-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_CD/n200/Weights_ReverseSource/" --source_model_id="/bime-munin/xiruod/llama2_CD/n200/Reverse-Source-set-3636-quantization-epoch3-llama-2-7B-loraR-8" --quantization --gpu="1" --lambda1='1.5' --lambda2='1.5' --cpuOps
python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_CD/n200/Weights_ReverseSource/set-3636-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_1.5-added.pth" --output_dir="/bime-munin/xiruod/llama2_CD/n200/Inferences_ReverseSource/" --quantization --gpu="1" --device="cuda:0" --batch_size=8 --cpuOps --dataset="CD"
python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_CD/n200/Inferences_ReverseSource/inference_set-3636-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_1.5-added" --output_dir="../output/tmpData/CD_ReverseSource/" --nRuns=5 --dataset="CD"

python run_editing_weights_loraMerge.py --target_model_id="/bime-munin/xiruod/llama2_CD/n200/set-3636-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_CD/n200/Weights_ReverseSource/" --source_model_id="/bime-munin/xiruod/llama2_CD/n200/Reverse-Source-set-3636-quantization-epoch3-llama-2-7B-loraR-8" --quantization --gpu="1" --lambda1='1.5' --lambda2='1.75' --cpuOps
python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_CD/n200/Weights_ReverseSource/set-3636-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_1.75-added.pth" --output_dir="/bime-munin/xiruod/llama2_CD/n200/Inferences_ReverseSource/" --quantization --gpu="1" --device="cuda:0" --batch_size=8 --cpuOps --dataset="CD"
python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_CD/n200/Inferences_ReverseSource/inference_set-3636-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_1.75-added" --output_dir="../output/tmpData/CD_ReverseSource/" --nRuns=5 --dataset="CD"

python run_editing_weights_loraMerge.py --target_model_id="/bime-munin/xiruod/llama2_CD/n200/set-3636-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_CD/n200/Weights_ReverseSource/" --source_model_id="/bime-munin/xiruod/llama2_CD/n200/Reverse-Source-set-3636-quantization-epoch3-llama-2-7B-loraR-8" --quantization --gpu="1" --lambda1='1.5' --lambda2='2.0' --cpuOps
python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_CD/n200/Weights_ReverseSource/set-3636-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_2.0-added.pth" --output_dir="/bime-munin/xiruod/llama2_CD/n200/Inferences_ReverseSource/" --quantization --gpu="1" --device="cuda:0" --batch_size=8 --cpuOps --dataset="CD"
python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_CD/n200/Inferences_ReverseSource/inference_set-3636-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_2.0-added" --output_dir="../output/tmpData/CD_ReverseSource/" --nRuns=5 --dataset="CD"

python run_editing_weights_loraMerge.py --target_model_id="/bime-munin/xiruod/llama2_CD/n200/set-3636-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_CD/n200/Weights_ReverseSource/" --source_model_id="/bime-munin/xiruod/llama2_CD/n200/Reverse-Source-set-3636-quantization-epoch3-llama-2-7B-loraR-8" --quantization --gpu="1" --lambda1='1.5' --lambda2='2.5' --cpuOps
python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_CD/n200/Weights_ReverseSource/set-3636-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_2.5-added.pth" --output_dir="/bime-munin/xiruod/llama2_CD/n200/Inferences_ReverseSource/" --quantization --gpu="1" --device="cuda:0" --batch_size=8 --cpuOps --dataset="CD"
python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_CD/n200/Inferences_ReverseSource/inference_set-3636-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_2.5-added" --output_dir="../output/tmpData/CD_ReverseSource/" --nRuns=5 --dataset="CD"

python run_editing_weights_loraMerge.py --target_model_id="/bime-munin/xiruod/llama2_CD/n200/set-3636-quantization-epoch3-llama-2-7B-loraR-8" --weightsEditedDir="/bime-munin/xiruod/llama2_CD/n200/Weights_ReverseSource/" --source_model_id="/bime-munin/xiruod/llama2_CD/n200/Reverse-Source-set-3636-quantization-epoch3-llama-2-7B-loraR-8" --quantization --gpu="1" --lambda1='1.5' --lambda2='3.0' --cpuOps
python run_edited_weights_InferenceOnly.py --weightsEdited="/bime-munin/xiruod/llama2_CD/n200/Weights_ReverseSource/set-3636-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_3.0-added.pth" --output_dir="/bime-munin/xiruod/llama2_CD/n200/Inferences_ReverseSource/" --quantization --gpu="1" --device="cuda:0" --batch_size=8 --cpuOps --dataset="CD"
python run_edited_weights_Eval.py --inferencePathPrefix="/bime-munin/xiruod/llama2_CD/n200/Inferences_ReverseSource/inference_set-3636-quantization-epoch3-llama-2-7B-loraR-8-lambda1_1.5-lambda2_3.0-added" --output_dir="../output/tmpData/CD_ReverseSource/" --nRuns=5 --dataset="CD"